<?php
/**
 * Main plugin initialization class
 *
 * @package WP_Ability_Toolkit
 */

namespace WP_Ability_Toolkit;

/**
 * Main plugin class that handles initialization
 */
class Plugin {
	/**
	 * Plugin version
	 */
	const VERSION = '0.1.0';

	/**
	 * Plugin file path
	 *
	 * @var string
	 */
	private $plugin_file;

	/**
	 * Settings instance
	 *
	 * @var Settings
	 */
	private $settings;

	/**
	 * REST API instance
	 *
	 * @var REST_API
	 */
	private $rest_api;

	/**
	 * Singleton instance
	 *
	 * @var Plugin|null
	 */
	private static $instance = null;

	/**
	 * Get singleton instance
	 *
	 * @param string $plugin_file Optional. Path to main plugin file.
	 * @return Plugin
	 */
	public static function get_instance( $plugin_file = '' ) {
		if ( null === self::$instance ) {
			self::$instance = new self( $plugin_file );
		}
		return self::$instance;
	}

	/**
	 * Constructor - private for singleton
	 *
	 * @param string $plugin_file Path to main plugin file.
	 */
	private function __construct( $plugin_file = '' ) {
		// Store plugin file path.
		if ( empty( $plugin_file ) ) {
			$plugin_file = dirname( __DIR__ ) . '/wp-ability-toolkit.php';
		}
		$this->plugin_file = $plugin_file;

		// Initialize core components.
		$this->settings = new Settings();
		$this->rest_api = new REST_API( $this->settings );
	}

	/**
	 * Initialize the plugin
	 */
	public function init() {
		// Load text domain for translations.
		add_action( 'init', array( $this, 'load_textdomain' ) );

		// Register settings.
		add_action( 'admin_init', array( $this->settings, 'register' ) );

		// Register REST API routes.
		add_action( 'rest_api_init', array( $this->rest_api, 'register_routes' ) );

		// Add settings page.
		add_action( 'admin_menu', array( $this, 'add_settings_page' ) );

		// Register Abilities API assets (when installed via Composer).
		add_action( 'init', array( 'WP_Abilities_Assets_Init', 'register_assets' ) );
		add_action( 'admin_enqueue_scripts', array( 'WP_Abilities_Assets_Init', 'admin_enqueue_scripts' ) );


		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_chat_widget' ), 20 );

		// Register test categories and abilities.
		add_action( 'abilities_api_categories_init', array( $this, 'register_test_categories' ) );
		add_action( 'abilities_api_init', array( $this, 'register_test_abilities' ) );

		// WordPress Ability API integration hook.
		do_action( 'wp_ability_toolkit_register_abilities' );
	}

	/**
	 * Load plugin textdomain for translations
	 */
	public function load_textdomain() {
		load_plugin_textdomain(
			'wp-ability-toolkit',
			false,
			dirname( plugin_basename( $this->plugin_file ) ) . '/languages'
		);
	}

	/**
	 * Add settings page to WordPress admin
	 */
	public function add_settings_page() {
		add_options_page(
			__( 'WP Ability Toolkit', 'wp-ability-toolkit' ),
			__( 'WP Ability Toolkit', 'wp-ability-toolkit' ),
			'manage_options',
			'wp-ability-toolkit-settings',
			array( $this, 'render_settings_page' )
		);
	}

	/**
	 * Render settings page
	 */
	public function render_settings_page() {
		echo '<div id="wp-ability-toolkit-settings-root"></div>';
	}

	/**
	 * Enqueue chat widget scripts
	 *
	 * @param string $hook Current admin page hook.
	 */
	public function enqueue_chat_widget( $hook ) {
		// Explicitly enqueue WordPress dependencies first.
		wp_enqueue_script( 'wp-element' );
		wp_enqueue_script( 'wp-components' );
		wp_enqueue_script( 'wp-abilities' ); // Ensure Abilities API is loaded.
		wp_enqueue_style( 'wp-components' );

		// Enqueue widget on all admin pages.
		// Note: wp-icons is not a real WordPress script handle, icons are bundled.
		$widget_js_path = dirname( $this->plugin_file ) . '/build/chat-widget/index.js';
		$widget_css_path = dirname( $this->plugin_file ) . '/build/chat-widget/index.css';
		$widget_asset_path = dirname( $this->plugin_file ) . '/build/chat-widget/index.asset.php';

		// Load asset file generated by @wordpress/scripts (contains dependencies and version).
		$widget_asset = file_exists( $widget_asset_path )
			? require $widget_asset_path
			: array(
				'dependencies' => array( 'wp-element', 'wp-components' ),
				'version'      => filemtime( $widget_js_path ),
			);

		wp_enqueue_script(
			'wp-ability-toolkit-chat-widget',
			plugins_url( 'build/chat-widget/index.js', $this->plugin_file ),
			$widget_asset['dependencies'],
			$widget_asset['version'],
			true
		);

		wp_enqueue_style(
			'wp-ability-toolkit-chat-widget',
			plugins_url( 'build/chat-widget/index.css', $this->plugin_file ),
			array( 'wp-components' ),
			filemtime( $widget_css_path )
		);

		// Set up script translations.
		wp_set_script_translations(
			'wp-ability-toolkit-chat-widget',
			'wp-ability-toolkit',
			dirname( $this->plugin_file ) . '/languages'
		);

		// Localize script with nonce and endpoint.
		wp_localize_script(
			'wp-ability-toolkit-chat-widget',
			'wpAbilityToolkit',
			array(
				'nonce'     => wp_create_nonce( 'wp_rest' ),
				'endpoint'  => rest_url( 'wp-ability-toolkit/v1/chat' ),
				'pluginUrl' => plugins_url( '', $this->plugin_file ),
			)
		);

		// Enqueue settings page script if on settings page.
		if ( 'settings_page_wp-ability-toolkit-settings' === $hook ) {
			$settings_js_path = dirname( $this->plugin_file ) . '/build/admin/settings.js';
			$settings_asset_path = dirname( $this->plugin_file ) . '/build/admin/settings.asset.php';

			// Load asset file generated by @wordpress/scripts.
			$settings_asset = file_exists( $settings_asset_path )
				? require $settings_asset_path
				: array(
					'dependencies' => array( 'wp-element', 'wp-components', 'wp-i18n' ),
					'version'      => filemtime( $settings_js_path ),
				);

			wp_enqueue_script(
				'wp-ability-toolkit-settings',
				plugins_url( 'build/admin/settings.js', $this->plugin_file ),
				$settings_asset['dependencies'],
				$settings_asset['version'],
				true
			);

			wp_enqueue_style( 'wp-components' );

			// Localize script for settings page.
			wp_localize_script(
				'wp-ability-toolkit-settings',
				'wpAbilityToolkitSettings',
				array(
					'nonce'            => wp_create_nonce( 'wp_rest' ),
					'settingsEndpoint' => rest_url( 'wp-ability-toolkit/v1/settings' ),
				)
			);
		}
	}

	/**
	 * Get settings instance
	 *
	 * @return Settings
	 */
	public function get_settings() {
		return $this->settings;
	}

	/**
	 * Get REST API instance
	 *
	 * @return REST_API
	 */
	public function get_rest_api() {
		return $this->rest_api;
	}

	/**
	 * Register core ability categories
	 */
	public function register_test_categories() {
		wp_register_ability_category(
			'data-retrieval',
			array(
				'label'       => __( 'Data Retrieval', 'wp-ability-toolkit' ),
				'description' => __( 'Abilities that retrieve and return data without modifying it', 'wp-ability-toolkit' ),
			)
		);

		wp_register_ability_category(
			'meta-tools',
			array(
				'label'       => __( 'Meta Tools', 'wp-ability-toolkit' ),
				'description' => __( 'Meta abilities that help you expand and debug the AI assistant\'s capabilities', 'wp-ability-toolkit' ),
			)
		);
	}

	/**
	 * Register core abilities
	 */
	public function register_test_abilities() {
		// Load server-side abilities from the abilities folder.
		require_once dirname( $this->plugin_file ) . '/includes/abilities/think.php';
		require_once dirname( $this->plugin_file ) . '/includes/abilities/create-ability.php';

		// Register server-side abilities.
		\WP_Ability_Toolkit\Abilities\register_think_ability();
		\WP_Ability_Toolkit\Abilities\register_create_ability();
	}
}
